WITH RNK_REVIEW AS (
SELECT MEMBER_ID,
       RANK() OVER(ORDER BY COUNT(MEMBER_ID) DESC) rnk
FROM REST_REVIEW
GROUP BY MEMBER_ID)

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, 
       DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE m JOIN REST_REVIEW r ON m.member_id=r.member_id
WHERE r.member_id IN (SELECT MEMBER_ID FROM RNK_REVIEW WHERE rnk=1)
ORDER BY 3, 2;